// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 04.07.2025 01:29:29
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/Users/ercan/OneDrive/Desktop/starter34/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ercan/OneDrive/Desktop/starter34/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ercan/OneDrive/Desktop/starter34/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ercan/OneDrive/Desktop/starter34/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ercan/OneDrive/Desktop/starter34/plugins/**/*.{js,ts,mjs}","C:/Users/ercan/OneDrive/Desktop/starter34/composables/**/*.{js,ts,mjs}","C:/Users/ercan/OneDrive/Desktop/starter34/utils/**/*.{js,ts,mjs}","C:/Users/ercan/OneDrive/Desktop/starter34/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ercan/OneDrive/Desktop/starter34/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ercan/OneDrive/Desktop/starter34/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ercan/OneDrive/Desktop/starter34/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;